config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about', to: "homes#about", as: "about"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }

  get '/search', to: "search#search", as: "search"

  get 'users/withdraw', to: 'users#withdraw',as: 'withdraw'
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :user_relationships, only: [:create, :destroy]
    get :followed, on: :member
    get :follower, on: :member
  end

  get '/infinite_scrolling', to: "pet_records#infinite_scrolling"
  get '/likes', to: 'likes#index',as: 'likes'
  get '/record_comments', to: 'record_comments#index',as: 'comments'
  get 'pet_records/tag', to: 'pet_records#tag',as: 'tag'
  resources :pet_records do
    resource :likes, only: [:create, :destroy]
  end
  resources :record_comments, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_action :authenticate_user!
	def search
		# @wordsはapplication_controllerで定義
		@words = @search.result(distinct: true)
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class="search-box">
    <table>
        <tr>
            <th></th>
            <!-- ソート機能 -->
            <th>
                <%= sort_link(@search, :user_name, "ひとのなまえ") %>
            </th>
            <th>
                <%= sort_link(@search, :user_pet_name, "どうぶつのなまえ") %>
            </th>
            <th>
                <%= sort_link(@search, :user_intoroduction, "プロフィール") %>
            </th>
            <th>
                <%= sort_link(@search, :body, "記録") %>
            </th>
            <th></th>
            <th></th>
        </tr>
        <!-- 検索結果 -->
        <% @words.each do |word| %>
          <% if(word.user.user_status == "公開")&&(word.record_public == true)%>
            <tr>
                <td>
                    <%= attachment_image_tag word.user, :profile_image, size: "70x70", fallback: "no-image.jpg", class: "img" %>
                </td>
                <td>
                    <%= link_to(user_path(word.user)) do %>
                    <%= word.user.name %>
                    <% end %>
                </td>
                <td>
                    <%= word.user.pet_name %>
                </td>
                <td>
                    <%= truncate(word.user.intoroduction, length: 20) %>
                </td>
                <td>
                    <%=  link_to(pet_record_path(word)) do %>
                     <%= truncate tag_word(word), length: 20 %>
                    <% end %>
                </td>
                <!-- タグ機能 -->
                <td>
                    <%= render "pet_records/tag", record: word %>
                </td>
                <!-- フォロー機能 -->
                <td>
                    <%= render 'users/follow', user: word.user %>
                </td>
            </tr>
          <% end %>
        <!-- if 公開 -->
        <% end %>
        <!-- words.each -->
    </table>
</div>