config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about', to: "homes#about", as: "about"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }

  get '/search', to: "search#search", as: "search"

  get 'users/withdraw', to: 'users#withdraw',as: 'withdraw'
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :user_relationships, only: [:create, :destroy]
    get :followed, on: :member
    get :follower, on: :member
  end

  get '/infinite_scrolling', to: "pet_records#infinite_scrolling"
  get '/likes', to: 'likes#index',as: 'likes'
  get '/record_comments', to: 'record_comments#index',as: 'comments'
  get 'pet_records/tag', to: 'pet_records#tag',as: 'tag'
  resources :pet_records do
    resource :likes, only: [:create, :destroy]
  end
  resources :record_comments, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # デバイス
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # 投稿
  has_many :pet_records, dependent: :destroy
  # いいね機能
  has_many :likes, dependent: :destroy
  has_many :like_pet_records, through: :likes, source: :pet_record
  # コメント
  has_many :record_comments, dependent: :destroy
  has_many :comments, through: :record_comments, source: :pet_record
  # フォロー
  has_many :active_relationships, class_name: "UserRelationship", foreign_key: :followed_id
  has_many :followeds, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "UserRelationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :followed
  # プロフィール画像
  attachment :profile_image, destroy: false

  enum user_status: { "公開"=>0, "非公開"=>1}

  # バリデーション
  with_options length: { in: 1..100 } do
    validates :name
    validates :pet_name
  end

  # フォロー
  def followed_by?(user)
    passive_relationships.find_by(followed_id: user.id).present?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :pet_name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :email])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #  super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
  edit_user_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.where(user_status: 0)
  end

  def show
    user = User.find(params[:id])
    if user.user_status == "公開" || user.id == current_user.id
      @user = user
      @pet_records = PetRecord.where(user_id: @user).order(created_at: :desc)
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def edit
    user = User.find(params[:id])
    if user.id == current_user.id
  	  @user = user
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def update
    user = User.find(current_user.id)
    user.update(user_params)
    redirect_to user_path(current_user)
  end

  def destroy
    user = User.find(current_user.id)
    user.destroy
    redirect_to root_path
  end

  def withdraw
  end

  def followed
    user = User.find(params[:id])
    if user.user_status == "公開" || user.id == current_user.id
      @users = user.followeds
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def follower
    user = User.find(params[:id])
    if user.user_status == "公開" || user.id == current_user.id
      @users = user.followers
    else
      redirect_back(fallback_location: root_url)
    end
   end


  private

  def user_params
    params.require(:user).permit(:name, :pet_name, :profile_image, :intoroduction, :user_status)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow-user_search.html.erb
<% users.each do |user| %>
	<% if user.user_status == "公開" %>
	  	<%= link_to(user_path(user)) do %>
		    <table>
		        <tr>
			        <td>
			            <%= user.name %>
			            <%= user.pet_name %>
			        </td>
		        </tr>
		        <tr>
		        	<td>
		            	<%= user.intoroduction %>
		        	</td>
		        </tr>
		        <tr>
		        	<td><%= attachment_image_tag user, :profile_image, size: "100x100" %></td>
		        </tr>
		        <tr>
		        	<td>
			        	<% if current_user.id != user.id %>
				            <% if user.followed_by?(current_user) %>
				                <p><%=link_to "フォロー済み", user_user_relationships_path(user.id), method: :delete %></p>
				            <% else %>
				                <p><%=link_to "フォローする", user_user_relationships_path(user.id), method: :post %></p>
				            <% end %>
				        <% end %>
		        	</td>
		        </tr>
		    </table>
		<% end %>
	<% end %>
<% end %>

app/views/users/_follow.html.erb
<% if current_user.id != user.id %>
  <% if user.followed_by?(current_user) %>
    <p class="follow">
        <%=link_to "フォロー済み", user_user_relationships_path(user.id), method: :delete, class: "btn btn-default active" %>
    </p>
  <% else %>
    <p class="follow">
        <%=link_to "フォローする", user_user_relationships_path(user.id), method: :post, class: "btn btn-default" %>
    </p>
  <% end %>
<% end %>

app/views/users/_index-follower-followed.html.erb
<% users.each do |user| %>
  <% if user.user_status == "公開" %>
    <div class="item-box">
        <div class="image-box">
            <%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no-image.jpg", class: "user-image" %>
        </div>
        <div class="items">
            <%= link_to(user_path(user)) do %>
            <span class="name">
                ひとのなまえ：
                <%= user.name %><br>
                どうぶつのなまえ：
                <%= user.pet_name %>
            </span>
            <span class="follow-user-intoroduction">
                <%= truncate(user.intoroduction, length: 20) %>
                　　</span>
            <% end %>
            <!-- フォロー機能 -->
            <%= render 'users/follow', user: user %>
        </div>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit">
    <%= form_with(model: @user, local: true) do |f| %>
    <table>
        <tr>
            <td>
                <%= f.attachment_field :profile_image, class: "img" %>
            </td>
        </tr>
        <tr>
            <td>
                <%= f.label :"ひとのなまえ", class: "user-name" %>
                <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
            </td>
        </tr>
        <tr>
            <td>
                <%= f.label :"どうぶつのなまえ",class: "pet-name" %>
                <%= f.text_field :pet_name, autofocus: true, autocomplete: "pet_name" %>
            </td>
        </tr>
        <tr>
            <td>
                <%= f.text_area :intoroduction, class: "user-intoroduction" %>
            </td>
        </tr>
        <tr>
            <td class="status-radio-button">
                <%= f.radio_button :user_status, "公開" %>
                <%= f.label :user_status, "公開" %>
                <%= f.radio_button :user_status, "非公開" %>
                <%= f.label :user_status, "非公開" %>
            </td>
        </tr>
        <tr>
            <td>
                <%= f.submit "更新", class: "btn btn-default user-btn" %>
            </td>
        </tr>
    </table>
    <%end%>
    <!-- デバイス部分の変更 -->
    <table>
        <tr>
            <td>
                <%= link_to 'メールアドレス・パスワードを変更する',edit_user_registration_path %>
            </td>
        </tr>
        <tr>
            <td>登録メールアドレス：
                <%= @user.email %>
            </td>
        </tr>
        <tr>
            <td>
                <%= link_to "ユーザーを削除する", withdraw_path %>
            </td>
        </tr>
    </table>
</div>

app/views/users/followed.html.erb
<div class="box">
    <%= render "index-follower-followed", users: @users %>
</div>

app/views/users/follower.html.erb
<div class="box">
    <%= render "index-follower-followed", users: @users %>
</div>

app/views/users/index.html.erb
<div class="box">
    <%= render "index-follower-followed", users: @users %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row user">
        <div class="image-public">
            <p class="public">
                <% if @user.user_status == "非公開" %>
                    プロフィール<br>
                    記録<br>
                    コメント<br>
                    ※ 非公開 ※
                <% end %>
            </p>
            <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", size: "100x100", fallback: "no-image.jpg", class: "image" %>
            <%if @user.id == current_user.id %>
                <%= link_to edit_user_path do %><i class="fas fa-cog gear fa-2x edit"></i>
                <% end %>
            <% end %>
        </div>
        <div class="user-status">
            <p class="name-font">
                <span>ひとのなまえ：</span>
                    <%= @user.name %> /
                <span>
                    どうぶつのなまえ：
                </span>
                <%= @user.pet_name %>
            </p>
            <p class="intoroduction-font">
                <%= @user.intoroduction %>
            </p>
            <p class="follow-font like comment">
                <%= link_to_unless_current  "ともした灯：#{ @user.likes.count} ", likes_path, class: "btn btn-default"  %>

                <% if @user.user_status == "公開" %>
                <%= link_to_unless_current  "コメント：#{ @user.record_comments.count} ", comments_path, class: "btn btn-default"  %>
                <% end %>


            <!-- フォロー機能 -->
                <%= link_to "フォロワー：#{ @user.followers.count }", follower_user_path(@user.id),  class: "btn btn-default" %>
                <%= link_to "フォロー：#{ @user.followeds.count }", followed_user_path(@user.id),  class: "btn btn-default" %>
            </p>
            <%= @user_continue %>
        </div>
    </div>
    <div class="row record">
        <% if @user.id == current_user.id %>
        <!-- カレンダー ※current userの場合表示-->
            <div class="col-lg-10">
                <%= month_calendar(attribute: :created_at,events: @pet_records)do |date, records| %>
                    <%= I18n.l(date, format: :short) %>
                    <% records.each do |record| %>
                        <span class="calendar-record">
                            <%= link_to pet_record_path(record) do %>
                            <p>
                                <%= record.energy %>：
                                <%= truncate tag_word(record), length: 8 %>
                            </p>
                            <% end %>
                        </span>
                    <% end %>
                <% end %>
            </div>
        <% else %>
        <!-- 記録一覧部分 -->
            <div class="col-lg-10">
                <div class="record-box" data-page="2">
                    <div>
                        <% @pet_records.each do |record| %>
                            <% if(@user.user_status == "公開")&&(record.record_public == true)%>
                                <%= render "pet_records/record-parts", record: record %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <div class="col-lg-2">
            <div class="date">
                <% @pet_records.each do |record| %>
                    <%= link_to(pet_record_path(record)) do %>
                        <table>
                            <tr>
                                <td>
                                    <%= l(record.created_at.to_date) %>
                                </td>
                            </tr>
                        </table>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/withdraw.html.erb
<p class="user-delete">ユーザーデータの削除をしますか
    <%= link_to "はい", @user, method: :delete %>
    <%= link_to "いいえ",user_path(current_user) %>
</p>