config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about', to: "homes#about", as: "about"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }

  get '/search', to: "search#search", as: "search"

  get 'users/withdraw', to: 'users#withdraw',as: 'withdraw'
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :user_relationships, only: [:create, :destroy]
    get :followed, on: :member
    get :follower, on: :member
  end

  get '/infinite_scrolling', to: "pet_records#infinite_scrolling"
  get '/likes', to: 'likes#index',as: 'likes'
  get '/record_comments', to: 'record_comments#index',as: 'comments'
  get 'pet_records/tag', to: 'pet_records#tag',as: 'tag'
  resources :pet_records do
    resource :likes, only: [:create, :destroy]
  end
  resources :record_comments, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet_record.rb
class PetRecord < ApplicationRecord

  # バリデーション
  validate :record_public_conditions
  validate :check_image

  # いいね機能のアソシエーション
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  # タグ機能のアソシエーション
  has_many :record_tags, dependent: :destroy
  has_many :tags, through: :record_tags
  belongs_to :user
  # コメントのアソシエーション
  has_many :record_comments, dependent: :destroy
  # 投稿画像の設定
  attachment :record_image, destroy: false

  # いいね機能
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end


  private

    # タグ機能の設定
    after_create do
      pet_record = PetRecord.find_by(id: self.id)
      tags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      tags.uniq.map do |t|
        tag = Tag.find_or_create_by(tag: t.gsub('＃', "#").delete("#"))
        pet_record.tags << tag
      end
    end

    before_update do
      pet_record = PetRecord.find_by(id: self.id)
      pet_record.tags.clear
      tags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      tags.uniq.map do |t|
        tag = Tag.find_or_create_by(tag: t.gsub('＃', "#").delete("#"))
        pet_record.tags << tag
      end
    end

    # 記録投稿時のバリデーション
    def record_public_conditions
      if body.blank? && record_image.blank? && record_public == true
       errors.add(:record_public, "をするためには文字か画像の入力が必要です")
      end
    end

    def check_image
      if !['.jpg', '.png', '.gif'].include?(File.extname(self.record_image_data[:filename]).downcase)
          errors.add(:record_image, "JPG, PNG, GIFのみアップロードできます。")
      end
    end
end

app/controllers/pet_records_controller.rb
class PetRecordsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :infinite_scrolling]

  def index
    @pet_records = PetRecord.where(record_public: true).order(created_at: :desc).page(params[:page]).per(8)
  end

  def new
    @pet_record = PetRecord.new
  end

  def create
    @pet_record = PetRecord.new(pet_record_params)
    @pet_record.user = current_user
    if  @pet_record.save
        redirect_to @pet_record
    else
      render "new"
    end
  end

  def show
    @record_comment = RecordComment.new
    pet_record = PetRecord.find(params[:id])
    if pet_record.user.user_status == "公開" && pet_record.record_public == true || pet_record.user_id == current_user.id
      @pet_record = pet_record
      @like_users = @pet_record.like_users
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def edit
    pet_record = PetRecord.find(params[:id])
    if pet_record.user_id == current_user.id
      @pet_record = pet_record
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def update
    @pet_record = PetRecord.find(params[:id])
    @pet_record.user = current_user
    if  @pet_record.update(pet_record_params)
        redirect_to pet_record_path(@pet_record)
    else
        render "edit"
    end
  end

  def destroy
    @pet_record = PetRecord.find(params[:id])
    @pet_record.destroy
    redirect_to user_path(current_user)
  end

  def tag
     @tag = Tag.find(params[:tag_id])
     @tag_pet_records = @tag.record_tags
  end

  def infinite_scrolling
    @pet_records = PetRecord.where(record_public: true).order(created_at: :desc).page(params[:page]).per(8)
    if @pet_records.total_pages < params[:page].to_i
      @next_page = "last"
      else
      @next_page = params[:page].to_i + 1
    end
    respond_to do |format|
      format.js
    end
  end



  private

    def pet_record_params
      params.require(:pet_record).permit(:toilet, :water, :food, :energy, :record_image, :body, :record_public, :user_id, :tag_ids)
    end
end

app/views/pet_records/_index.html.erb
<% pet_records.each do |record| %>
  <% if record.user.user_status == "公開" %>
    <%= render "record-parts", record: record %>
  <% end %>
<% end %>

app/views/pet_records/_new-edit.html.erb
<%= form_with(model: pet_record, local: true) do |f| %>
	<% if pet_record.errors.any? %>
		<p>入力した内容にエラーが
		    <%= pet_record.errors.count %>件あります</p>
		<div class="alert alert-danger">
		    <ul>
		        <% pet_record.errors.full_messages.each do |message| %>
			        <li>
			            <%= message %>
			        </li>
		        <% end %>
		    </ul>
		</div>
	<% end %>
	<div class="status-radio-button">
	    <table>
	        <tr>
	            <th>トイレ</th>
	            <td>
	                <%= f.radio_button :toilet, "×" , id: "radio-1-1" %>
	                <%= f.label "×", for: "radio-1-1" %>
	            </td>
	            <td>
	                <%= f.radio_button :toilet, "△", id: "radio-1-2", :checked => true %>
	                <%= f.label "△", for: "radio-1-2" %>
	            </td>
	            <td>
	                <%= f.radio_button :toilet, "◯", id: "radio-1-3" %>
	                <%= f.label"◯", for: "radio-1-3" %>
	            </td>
	        </tr>
	        <tr>
	            <th>おみず</th>
	            <td>
	                <%= f.radio_button :water, "×", id: "radio-2-1" %>
	                <%= f.label"×", for: "radio-2-1" %>
	            </td>
	            <td>
	                <%= f.radio_button :water, "△", id: "radio-2-2", :checked => true %>
	                <%= f.label"△", for: "radio-2-2" %>
	            </td>
	            <td>
	                <%= f.radio_button :water, "◯", id: "radio-2-3" %>
	                <%= f.label"◯", for: "radio-2-3" %>
	            </td>
	        </tr>
	        <tr>
	            <th>ごはん</th>
	            <td>
	                <%= f.radio_button :food, "×", id: "radio-3-1" %>
	                <%= f.label"×", for: "radio-3-1" %>
	            </td>
	            <td>
	                <%= f.radio_button :food, "△", id: "radio-3-2", :checked => true %>
	                <%= f.label"△", for: "radio-3-2" %>
	            </td>
	            <td>
	                <%= f.radio_button :food, "◯", id: "radio-3-3" %>
	                <%= f.label"◯", for: "radio-3-3" %>
	            </td>
	        </tr>
	        <tr>
	            <th>げんき</th>
	            <td>
	                <%= f.radio_button :energy, "×", id: "radio-4-1" %>
	                <%= f.label"×", for: "radio-4-1" %>
	            </td>
	            <td>
	                <%= f.radio_button :energy, "△", id: "radio-4-2", :checked => true %>
	                <%= f.label"△", for: "radio-4-2" %>
	            </td>
	            <td>
	                <%= f.radio_button :energy, "◯", id: "radio-4-3" %>
	                <%= f.label"◯", for: "radio-4-3" %>
	            </td>
	            </td>
	        </tr>
	    </table>
	    <div class="record">
	        <%= f.attachment_field :record_image, class: "img" %>
	        <%= f.text_area :body, class: "text-form" %>
	    </div>
	    <div class="status-radio-button">
	        <% if current_user.user_status == "非公開" %>
	        	<%= "非公開"%>
	        <% else %>
		        <%= f.radio_button :record_public, :true, id: "radio-5-1" %>
		        <%= f.label :公開, for: "radio-5-1" %>
		        <%= f.radio_button :record_public, :false, id: "radio-5-2" %>
		        <%= f.label :非公開, for: "radio-5-2" %>
	        <% end %>
	    </div>
	    <%= f.submit "記録", class: "btn btn-default record-btn" %>
	</div>
<% end %>

app/views/pet_records/_record-parts.html.erb
<div class="record-box-item">
    <ul>
        <li class="record-image">
            <%= attachment_image_tag record, :record_image, size: "100x100%", class: "img" %>
        </li>
    </ul>
    <ul>
        <li class="date">
            <%= link_to(pet_record_path(record)) do %>
              <%= l(record.created_at.to_date) %>
            <% end %>
        </li>
        <li class="record-body">
            <%= truncate tag_word(record), length: 30 %>
        </li>
    </ul>
    <ul>
        <li class="user-pet-name">
            <%= link_to user_path(record.user.id) do %>
              公開者：
              <%= record.user.name %>
            <% end %>
        </li>
    </ul>
    <ul>
        <li>
            <div class="like-comment">
            <!-- コメント機能 -->
                <span class="comment-count">
                <%= record.record_comments.count %>件コメント
                </span>

            <!-- いいね機能 -->
                <span id="likes_buttons_<%= record.id %>">
                    <%= render 'likes/like', pet_record: record %>
                </span>
            </div>
        </li>
        <!-- タグ機能 -->
        <li class="tag">
            <%= render "pet_records/tag", record: record %>
        </li>
    </ul>
    <ul>
    </ul>
    <ul>
        <li class="pet-status">
            トイレ
            <%= record.toilet %>
            お水
            <%= record.water %>
            ごはん
            <%= record.food %>
            元気
            <%= record.energy %>
        </li>
    </ul>
</div>

app/views/pet_records/_tag.html.erb
<!-- タグ機能 -->
<% if record.tags.any? %>
  <% record.tags.each do |tag| %>
    <%= link_to tag_path(tag_id: tag.id) do %>
      #<%= tag.tag %>
    <% end %>
  <% end %>
<% end %>

app/views/pet_records/edit.html.erb
<div class="new-edit-box">
    <%= render 'new-edit', pet_record: @pet_record %>
</div>

app/views/pet_records/index.html.erb
<% if user_signed_in? == false %>
  <div class="about">
      <%= link_to "アバウト『YOU □ ME』", about_path %>
  </div>
  <div class="enter">
      <%= link_to "サインイン", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "ホーム", root_path %>
  </div>
<% end %>
<div class="record-box" data-page="2">
    <div>
        <%= render "pet_records/index", pet_records: @pet_records %>
    </div>
    <span class="loader-container d-none"></span>
</div>
<%= javascript_include_tag 'scrolling.js' %>

app/views/pet_records/infinite_scrolling.js.erb
if ("<%=@next_page%>" != "last") {
    $(".record-box > div").append("<%= escape_javascript(render 'pet_records/index', pet_records: @pet_records) %>")
    $(".loader-container").addClass("d-none")
} else {}
$(".record-box").attr('data-page', "<%=@next_page%>")

app/views/pet_records/new.html.erb
<div class="new-edit-box">
  <%= render 'new-edit', {pet_record: @pet_record, err: @err }%>
</div>

app/views/pet_records/show.html.erb
<div class="show-record-box">
    <table class="record-table">
        <tr>
            <td class="date-box">
                <h3>
                    <%= l(@pet_record.created_at.to_date) %>
                </h3>
            </td>
        </tr>
        <tr>
            <td class="name-box">
                <span>ひとのなまえ：</span>
                <%= @pet_record.user.name %>/<span>どうぶつのなまえ：</span>
                <%= @pet_record.user.pet_name %>
            </td>
        </tr>
        <tr>
            <td class="pet-status" , style="line-height: 2em">
                トイレ：
                <%= @pet_record.toilet %> /
                お水：
                <%= @pet_record.water %> /
                ごはん：
                <%= @pet_record.food %> /
                元気：
                <%= @pet_record.energy %>
            </td>
        </tr>
        <tr>
            <td class="show-record_image">
                <%= attachment_image_tag @pet_record, :record_image, class: "img" %>
            </td>
        </tr>
        <% if @pet_record.record_public == false %>
            <tr>
                <td class="record_public">＊この記事は非公開です。＊</td>
            </tr>
        <% end %>
        <tr>
            <td class="body-box">
                <p class="show-body">
                    <%= tag_word(@pet_record) %>
                </p>
            </td>
        </tr>
        <!-- タグ機能 -->
        <tr>
            <td class="tag">
                <%= render "pet_records/tag", record: @pet_record %>
            </td>
        </tr>
        <tr>
            <% if user_signed_in? %>
                <td class="like">
                    <!-- いいね機能 -->
                    <span id="likes_buttons_<%= @pet_record.id %>">
                        <%= render 'likes/like', pet_record: @pet_record %>
                    </span>
                </td>
            <% end %>
        </tr>
        <% if @like_users.empty? == false %>
            <tr>
                <td>
                    <p class="liked-user"> この記録に灯をともしたユーザー</p>
                    <% @like_users.each do | like | %>
                        <% if like.user_status == "公開" %>
                            <%= link_to user_path(like) do %>
                                <%= attachment_image_tag like, :profile_image, size: "50x50", fallback: "no-image.jpg", class: "image" %>
                            <% end %>
                        <% end %>
                    <% end %>
                </td>
            </tr>
        <% end %>
        <tr>
            <td class = "comment-show">
                <p class = "comment-title1">コメント</p>
                <% @pet_record.record_comments.each do | c | %>
                    <% if c.user.user_status == "公開" %>
                        <div class="comment-box">
                            <%= attachment_image_tag c.user, :profile_image, size: "10x10", fallback: "no-image.jpg", class: "image" %>
                            <div class="comment-text-box">
                                <%= c.comment %>
                            </div>
                            <% if(c.user_id == current_user.id)%>
                                <div class="comment-delete">
                                    <%= link_to "コメントの削除", c, method: :delete, "data-confirm" => "本当に削除しますか？"  %>
                                </div>
                            <% end %>
                        </div>
                    <% end %>
                <% end %>
            </td>
        </tr>
        <tr>
            <td class = "comment-new">
                <p cless = "comment-title2">コメント（100文字まで）</p>
                <%= form_with model: @record_comment, class: "comment-form", local: true do |comment| %>
                    <% if @record_comment.errors.any? %>
                    <p>入力した内容にエラーが
                        <%= @record_comment.errors.count %>件あります</p>
                    <div class="alert alert-danger">
                        <ul>
                        <% @record_comment.errors.full_messages.each do |message| %>
                            <li>
                                <%= message %>
                            </li>
                        <% end %>
                        </ul>
                    </div>
                    <% end %>
                    <% if current_user.user_status == "公開" %>
                        <%= comment.text_area :comment, class: "comment-text" %>
                        <%= comment.hidden_field :pet_record_id, value: @pet_record.id %>
                        <%= comment.submit "送信する", class: "btn btn-default comment-submit" %>
                    <% else %>
                        <p class="private-comment">※　プロフィールが非公開の場合コメントはできません　※
                        </p>
                    <% end %>
                <% end %>
            </td>
        </tr>
        <tr>
            <td>
                <% if user_signed_in? %>
                    <% if(@pet_record.user_id == current_user.id)%>
                        <%= link_to "きろくの編集", edit_pet_record_path(@pet_record) %> /
                        <%= link_to "きろくの削除", @pet_record, method: :delete, "data-confirm" => "本当に削除しますか？"  %>
                    <% end %>
                <% end %>
            </td>
        </tr>
        <tr>
            <td class="link">
                <%= link_to_unless_current  "このきろくの投稿者のページ",  user_path(@pet_record.user.id) %> |
                <%= link_to_unless_current  "公開されているきろく",  pet_records_path %>
            </td>
        </tr>
    </table>
</div>

app/views/pet_records/tag.html.erb
<div class="box">
    <div class="tag-box">
      ＃<%= @tag.tag %>
    </div>
    <% @tag_pet_records.each do |tag| %>
      <%= render 'likes/like-tag-comme', record: tag.pet_record %>
    <% end %>
</div>