config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about', to: "homes#about", as: "about"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }

  get '/search', to: "search#search", as: "search"

  get 'users/withdraw', to: 'users#withdraw',as: 'withdraw'
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :user_relationships, only: [:create, :destroy]
    get :followed, on: :member
    get :follower, on: :member
  end

  get '/infinite_scrolling', to: "pet_records#infinite_scrolling"
  get '/likes', to: 'likes#index',as: 'likes'
  get '/record_comments', to: 'record_comments#index',as: 'comments'
  get 'pet_records/tag', to: 'pet_records#tag',as: 'tag'
  resources :pet_records do
    resource :likes, only: [:create, :destroy]
  end
  resources :record_comments, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

private

def tag_word(word)
  word.body.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/, "")
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :pet_record
	belongs_to :user
end

app/models/pet_record.rb
class PetRecord < ApplicationRecord

  # バリデーション
  validate :record_public_conditions
  validate :check_image

  # いいね機能のアソシエーション
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  # タグ機能のアソシエーション
  has_many :record_tags, dependent: :destroy
  has_many :tags, through: :record_tags
  belongs_to :user
  # コメントのアソシエーション
  has_many :record_comments, dependent: :destroy
  # 投稿画像の設定
  attachment :record_image, destroy: false

  # いいね機能
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end


  private

    # タグ機能の設定
    after_create do
      pet_record = PetRecord.find_by(id: self.id)
      tags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      tags.uniq.map do |t|
        tag = Tag.find_or_create_by(tag: t.gsub('＃', "#").delete("#"))
        pet_record.tags << tag
      end
    end

    before_update do
      pet_record = PetRecord.find_by(id: self.id)
      pet_record.tags.clear
      tags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      tags.uniq.map do |t|
        tag = Tag.find_or_create_by(tag: t.gsub('＃', "#").delete("#"))
        pet_record.tags << tag
      end
    end

    # 記録投稿時のバリデーション
    def record_public_conditions
      if body.blank? && record_image.blank? && record_public == true
       errors.add(:record_public, "をするためには文字か画像の入力が必要です")
      end
    end

    def check_image
      if !['.jpg', '.png', '.gif'].include?(File.extname(self.record_image_data[:filename]).downcase)
          errors.add(:record_image, "JPG, PNG, GIFのみアップロードできます。")
      end
    end
end

app/models/record_comment.rb
class RecordComment < ApplicationRecord
  validates :comment, length: { in: 1..100 }

  belongs_to :user
  belongs_to :pet_record

end

app/models/record_tag.rb
class RecordTag < ApplicationRecord
	belongs_to :pet_record
	belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :record_tags, dependent: :destroy
	has_many :pet_records, through: :record_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # デバイス
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # 投稿
  has_many :pet_records, dependent: :destroy
  # いいね機能
  has_many :likes, dependent: :destroy
  has_many :like_pet_records, through: :likes, source: :pet_record
  # コメント
  has_many :record_comments, dependent: :destroy
  has_many :comments, through: :record_comments, source: :pet_record
  # フォロー
  has_many :active_relationships, class_name: "UserRelationship", foreign_key: :followed_id
  has_many :followeds, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "UserRelationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :followed
  # プロフィール画像
  attachment :profile_image, destroy: false

  enum user_status: { "公開"=>0, "非公開"=>1}

  # バリデーション
  with_options length: { in: 1..100 } do
    validates :name
    validates :pet_name
  end

  # フォロー
  def followed_by?(user)
    passive_relationships.find_by(followed_id: user.id).present?
  end

end

app/models/user_relationship.rb
class UserRelationship < ApplicationRecord
	belongs_to :followed, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 before_action :authenticate_user!

  def index
    @like_pet_records = current_user.like_pet_records
  end

  def create
    @pet_record = PetRecord.find(params[:pet_record_id])
    like = current_user.likes.new(pet_record_id: @pet_record.id)
    like.save
  end

  def destroy
  	@pet_record = PetRecord.find(params[:pet_record_id])
    like = current_user.likes.find_by(pet_record_id: @pet_record.id)
    like.destroy
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_action :authenticate_user!
	def search
		# @wordsはapplication_controllerで定義
		@words = @search.result(distinct: true)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.where(user_status: 0)
  end

  def show
    user = User.find(params[:id])
    if user.user_status == "公開" || user.id == current_user.id
      @user = user
      @pet_records = PetRecord.where(user_id: @user).order(created_at: :desc)
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def edit
    user = User.find(params[:id])
    if user.id == current_user.id
  	  @user = user
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def update
    user = User.find(current_user.id)
    user.update(user_params)
    redirect_to user_path(current_user)
  end

  def destroy
    user = User.find(current_user.id)
    user.destroy
    redirect_to root_path
  end

  def withdraw
  end

  def followed
    user = User.find(params[:id])
    if user.user_status == "公開" || user.id == current_user.id
      @users = user.followeds
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def follower
    user = User.find(params[:id])
    if user.user_status == "公開" || user.id == current_user.id
      @users = user.followers
    else
      redirect_back(fallback_location: root_url)
    end
   end


  private

  def user_params
    params.require(:user).permit(:name, :pet_name, :profile_image, :intoroduction, :user_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/linkes_helper.rb
module LinkesHelper
end

app/helpers/record_comments_helper.rb
module RecordCommentsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_relationships_helper.rb
module UserRelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>YOU □ ME</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/1eca3cbf72.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
</head>

<body data-turbolinks="false">
    <% if user_signed_in? %>
      <header>
          <nav>
              <!-- ユーザーログイン済の時のみヘッダー表示 -->
              <div class="title">
                  <h1>
                      YOU □ ME
                  </h1>
                  <h5>
                      <%= I18n.l(Date.today) %>
                  </h5>
              </div>
              <ul>
                <li>
                  <%= link_to_unless_current  "新しい記録",new_pet_record_path %>
                </li>
                <li>
                      <%= link_to_unless_current  "マイページ",  user_path(current_user) %>
                  </li>
                  <li>
                      <%= link_to_unless_current  "公開されているきろく",  pet_records_path %>
                  </li>
                  <li>
                      <%= link_to_unless_current  "公開しているユーザー",  users_path %>
                  </li>
                  <li>
                      <%= link_to_unless_current  "ログアウト",  destroy_user_session_path, method: :delete  %>
                  </li>
                  <li>
                      <%= link_to "アバウト", about_path %>
                  </li>
                  <li>
                      <%= link_to "ホーム", root_path %>
                  </li>
              </ul>
              <!-- 検索機能 -->
              <%= search_form_for @search, url:search_path do |search| %>
                <div class="input-group">
                    <%= search.search_field :user_name_or_user_pet_name_or_user_intoroduction_or_body_cont_any, class: "form-control", placeholder: "検索" %>
                    <span class="input-group-btn">
                        <%= search.submit "検索", class: "btn btn-default search" %>
                    </span>
                </div>
              <% end %>
          </nav>
      </header>
    <% end %>
    <%= yield %>
</body>

</html>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
    <div class="calendar-heading">
        <%= link_to t('simple_calendar.previous', default: '前の月'), calendar.url_for_previous_view %>
        <span class="calendar-title">
            <%= start_date.year %>年
            <%= t('date.month_names')[start_date.month] %>
        </span>
        <%= link_to t('simple_calendar.next', default: '次の月'), calendar.url_for_next_view %>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <% date_range.slice(0, 7).each do |day| %>
                  <th class="week">
                      <p>
                          <%= t('date.abbr_day_names')[day.wday] %>
                      </p>
                  </th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% date_range.each_slice(7) do |week| %>
              <tr class="day">
                  <% week.each do |day| %>
                    <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                      <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                        <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
                      <% else %>
                        <% block.call day, sorted_events.fetch(day, []) %>
                      <% end %>
                    <% end %>
                  <% end %>
              </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
    <div class="calendar-heading">
        <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
        <% if calendar.number_of_weeks == 1 %>
          <span class="calendar-title">Week
              <%= calendar.week_number %></span>
        <%else%>
          <span class="calendar-title">Week
              <%= calendar.week_number %> -
              <%= calendar.end_week %></span>
        <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <% date_range.slice(0, 7).each do |day| %>
                  <th>
                      <%= t('date.abbr_day_names')[day.wday] %>
                  </th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% date_range.each_slice(7) do |week| %>
              <tr>
                  <% week.each do |day| %>
                    <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                      <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                        <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
                      <% else %>
                        <% block.call day, sorted_events.fetch(day, []) %>
                      <% end %>
                    <% end %>
                  <% end %>
              </tr>
            <% end %>
        </tbody>
    </table>
</div>